image: gitpod/workspace-base

tasks:
- name: install mamba and omark
  init: |
    curl -L -O "https://github.com/conda-forge/miniforge/releases/latest/download/Mambaforge-$(uname)-$(uname -m).sh"
    bash Mambaforge-$(uname)-$(uname -m).sh -b -p /workspace/conda && rm Mambaforge-$(uname)-$(uname -m).sh
    /workspace/conda/bin/mamba init bash
    source ${HOME}/.bashrc
    mamba create -n omacademy -c conda-forge python=3.9 -y
    mamba activate omacademy
    cd SIBComparativeGenomics2023/Module3_FastOMA/working_dir/
    wget https://github.com/DessimozLab/FastOMA/archive/refs/heads/master.zip
    unzip master.zip
    mv FastOMA-master FastOMA
    pip install  ./FastOMA
    cd ../../../
    mamba install -c bioconda mafft -y 
    mamba install -c bioconda fasttree -y
    conda install -c conda-forge openjdk -y
    cd SIBComparativeGenomics2023/Module4_SpeciesTrees/working_dir/
    git clone https://github.com/DessimozLab/f1000_PhylogeneticTree.git
    echo 'export PATH=$PATH:/workspace/SIBComparativeGenomics2023/Module4_SpeciesTrees/working_dir/f1000_PhylogeneticTree/' >> ${HOME}/.bashrc
    echo 'mamba activate omacademy' >> ${HOME}/.bashrc
    cd ../../../
  command: |
    source ${HOME}/.bashrc

- name: Get OMAMer databases
  init: |
          cd /workspace
          curl -L -O "https://oma-stage.vital-it.ch/All/Metazoa.h5"
          curl -L -O "https://oma-stage.vital-it.ch/All/Saccharomyceta.h5"
          cp Saccharomyceta.h5 SIBComparativeGenomics2023/Module3_FastOMA/working_dir/in_folder/omamerdb.h5
          mv Saccharomyceta.h5 SIBComparativeGenomics2023/Module2_OMAmer/working_dir/omamer_databases/
          mv Metazoa.h5 SIBComparativeGenomics2023/Module2_OMAmer/working_dir/omamer_databases/
vscode:
  extensions:
    - anwar.papyrus-pdf

workspaceLocation: "/workspace"
